_target_: src.model.DeepSpeech2ModelNew

n_feats: 128          # Input frequency dimension
# n_tokens: 29          # Output vocabulary size
rnn_hidden: 768      # Hidden size from paper
rnn_layers: 5     # Number of RNN layers
bidirectional: True   # Use bidirectional RNNs