_target_: torch.utils.data.DataLoader
batch_size: 240 # 10 default; 80 works for server without BPE
num_workers: 32 # 32 # 16 # 2 default
pin_memory: True
persistent_workers: True # True # False
shuffle: True
# prefetch_factor: 2  # Preload 2 batches per worker
# timeout: 20 # temp fix for bad batches
