train:
  get_spectrogram: # special key for getting spectrogram
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
  audio:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.gain.Gain
        min_gain_in_db: -15
        max_gain_in_db: 5
        p: 0.5
      - _target_: src.transforms.wav_augs.PitchShift
        min_transpose_semitones: -4
        max_transpose_semitones: 4
        p: 0.5
        sample_rate: 16000
      - _target_: src.transforms.wav_augs.AddBackgroundNoise
        background_paths: noise_samples
        sample_rate: 16000
        p: 0.5
  spectrogram:  # New section for spectrogram augmentations
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.spec_augs.FrequencyMasking
        freq_mask_param: 20
      - _target_: src.transforms.spec_augs.TimeMasking
        time_mask_param: 30
inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
